import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "@/lib/auth";
import { format } from "date-fns";
import * as XLSX from "xlsx";

export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const searchParams = request.nextUrl.searchParams;
    const from = searchParams.get("from");
    const to = searchParams.get("to");
    const exportType = searchParams.get("type") || "bookings";

    const where: any = {
      customerName: { not: 'Temporary Lock' }
    };

    if (from && to) {
      where.createdAt = {
        gte: new Date(from),
        lte: new Date(to),
      };
    }

    if (exportType === "summary") {
      return await exportSummaryExcel(where);
    }

    // Default: Export detailed bookings
    const bookings = await prisma.booking.findMany({
      where,
      include: {
        facility: true,
        user: {
          select: {
            name: true,
            email: true,
          },
        },
        reviews: true,
      },
      orderBy: { createdAt: "desc" },
    });

    // Create workbook
    const wb = XLSX.utils.book_new();
    
    // Prepare data
    const exportDate = format(new Date(), "MMMM dd, yyyy 'at' HH:mm");
    const dateRange = from && to ? `For the Period [${format(new Date(from), 'MMM dd, yyyy')} to ${format(new Date(to), 'MMM dd, yyyy')}]` : 'All Time';
    
    const data: any[][] = [
      ["MANUEL RESORT"],
      ["Booking Report"],
      [dateRange],
      [],
      ["Report Summary"],
      ["Generated:", exportDate],
      ["Total Records:", bookings.length],
      [],
      ["Booking Details"],
      [],
      ["Booking Code", "Status", "Customer Name", "Email", "Phone", "Facility", "Type", "Check-In", "Check-Out", "Nights", "Guests", "Amount", "Booked On", "Confirmed On", "Rating", "Notes"],
    ];

    // Add booking rows
    bookings.forEach((booking) => {
      const nights = (booking.endDate.getTime() - booking.startDate.getTime()) / (1000 * 60 * 60 * 24);
      const firstReview = booking.reviews && booking.reviews.length > 0 ? booking.reviews[0] : null;
      
      data.push([
        booking.code,
        booking.status,
        booking.customerName,
        booking.customerEmail,
        booking.customerPhone || "-",
        booking.facility.name,
        booking.facility.kind,
        format(booking.startDate, "MMM dd, yyyy"),
        format(booking.endDate, "MMM dd, yyyy"),
        nights,
        booking.guests || "-",
        Number(booking.totalAmount),
        format(booking.createdAt, "MMM dd, yyyy HH:mm"),
        booking.confirmedAt ? format(booking.confirmedAt, "MMM dd, yyyy HH:mm") : "-",
        firstReview?.rating ? `${firstReview.rating}/5` : "-",
        booking.notes || "-",
      ]);
    });

    // Add totals
    const totalAmount = bookings.reduce((sum, b) => sum + Number(b.totalAmount), 0);
    const totalGuests = bookings.reduce((sum, b) => sum + (b.guests || 0), 0);
    
    data.push([]);
    data.push(["Total Bookings", "", "", "", "", "", "", "", "", totalGuests, totalAmount]);
    data.push([]);
    data.push([`© ${new Date().getFullYear()} Manuel Resort`, "", "", "", "", "", "", "", "", "", "", "", "", "", "Generated by Manuel Resort Booking System"]);

    // Create worksheet
    const ws = XLSX.utils.aoa_to_sheet(data);

    // Set column widths
    ws['!cols'] = [
      { wch: 15 }, // Booking Code
      { wch: 12 }, // Status
      { wch: 20 }, // Customer Name
      { wch: 25 }, // Email
      { wch: 15 }, // Phone
      { wch: 20 }, // Facility
      { wch: 10 }, // Type
      { wch: 15 }, // Check-In
      { wch: 15 }, // Check-Out
      { wch: 8 },  // Nights
      { wch: 8 },  // Guests
      { wch: 12 }, // Amount
      { wch: 20 }, // Booked On
      { wch: 20 }, // Confirmed On
      { wch: 10 }, // Rating
      { wch: 30 }, // Notes
    ];

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, "Booking Report");

    // Generate Excel file
    const excelBuffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
    const filename = `Manuel-Resort-Bookings-${format(new Date(), "yyyy-MM-dd-HHmmss")}.xlsx`;

    return new NextResponse(excelBuffer, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Excel export error:", error);
    return NextResponse.json(
      { error: "Failed to export data" },
      { status: 500 }
    );
  }
}

async function exportSummaryExcel(where: any) {
  const [totalBookings, totalRevenue, bookingsByStatus, bookingsByType] = await Promise.all([
    prisma.booking.count({ where }),
    prisma.booking.aggregate({
      where: {
        ...where,
        status: { in: ["CONFIRMED", "COMPLETED", "CHECKED_OUT"] },
      },
      _sum: { totalAmount: true },
    }),
    prisma.booking.groupBy({
      by: ["status"],
      where,
      _count: true,
      _sum: { totalAmount: true },
    }),
    prisma.booking.groupBy({
      by: ["facilityId"],
      where,
      _count: true,
      _sum: { totalAmount: true },
    }),
  ]);

  const facilities = await prisma.facility.findMany({
    where: {
      id: { in: bookingsByType.map((b) => b.facilityId) },
    },
  });

  const totalRev = Number(totalRevenue._sum.totalAmount || 0);

  // Create workbook
  const wb = XLSX.utils.book_new();

  const data: any[][] = [
    ["MANUEL RESORT"],
    ["Financial Summary Report"],
    [`For the Period Ending ${format(new Date(), 'MMM dd, yyyy')}`],
    [],
    ["Revenue Summary"],
    ["Total Bookings", totalBookings],
    ["Total Revenue", "", "", totalRev],
    [],
    ["Revenue by Status"],
    ["Status", "Count", "", "Revenue (₱)"],
  ];

  bookingsByStatus.forEach((stat) => {
    data.push([
      `  ${stat.status.replace(/_/g, ' ')}`,
      stat._count,
      "",
      Number(stat._sum.totalAmount || 0),
    ]);
  });

  data.push(["Total Revenue", "", "", totalRev]);
  data.push([]);
  data.push(["Revenue by Facility"]);
  data.push(["Facility", "Type", "Bookings", "Revenue (₱)"]);

  bookingsByType.forEach((stat) => {
    const facility = facilities.find((f) => f.id === stat.facilityId);
    data.push([
      `  ${facility?.name || "Unknown"}`,
      facility?.kind || "Unknown",
      stat._count,
      Number(stat._sum.totalAmount || 0),
    ]);
  });

  data.push(["Total Revenue", "", "", totalRev]);
  data.push([]);
  data.push([`© ${new Date().getFullYear()} Manuel Resort`, "", "", "Generated by Manuel Resort Booking System"]);

  const ws = XLSX.utils.aoa_to_sheet(data);

  ws['!cols'] = [
    { wch: 30 },
    { wch: 15 },
    { wch: 12 },
    { wch: 15 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, "Summary Report");

  const excelBuffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  const filename = `summary-report-${format(new Date(), "yyyy-MM-dd-HHmmss")}.xlsx`;

  return new NextResponse(excelBuffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
